spring:
  jpa:
    hibernate:
      - ddl-auto=update
  datasource:
    - url: ${JDBC_DATABASE_URL}
    - username: ${JDBC_DATABASE_USERNAME}
    - password: ${JDBC_DATABASE_PASSWORD}
    - driver-class-name: org.postgresql.Driver

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds